repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 8d41a13a731d43fda68af0e20a99a879c294950d #v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--hide providers
      - id: terraform_tfsec
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b # v4.5.0
    hooks:
      - id: trailing-whitespace